name: Java CI
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
 
    - name: List files in the directory
      run: ls -la
 
    - name: Compile Java program
      run: javac  App.java
 
    - name: Run Java program
      run: java App
